// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tgoodwin/sleeve/pkg/event (interfaces: Emitter)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	event "github.com/tgoodwin/sleeve/pkg/event"
	snapshot "github.com/tgoodwin/sleeve/pkg/snapshot"
)

// MockEmitter is a mock of Emitter interface.
type MockEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockEmitterMockRecorder
}

// MockEmitterMockRecorder is the mock recorder for MockEmitter.
type MockEmitterMockRecorder struct {
	mock *MockEmitter
}

// NewMockEmitter creates a new mock instance.
func NewMockEmitter(ctrl *gomock.Controller) *MockEmitter {
	mock := &MockEmitter{ctrl: ctrl}
	mock.recorder = &MockEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmitter) EXPECT() *MockEmitterMockRecorder {
	return m.recorder
}

// LogObjectVersion mocks base method.
func (m *MockEmitter) LogObjectVersion(arg0 snapshot.Record) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogObjectVersion", arg0)
}

// LogObjectVersion indicates an expected call of LogObjectVersion.
func (mr *MockEmitterMockRecorder) LogObjectVersion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogObjectVersion", reflect.TypeOf((*MockEmitter)(nil).LogObjectVersion), arg0)
}

// LogOperation mocks base method.
func (m *MockEmitter) LogOperation(arg0 *event.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogOperation", arg0)
}

// LogOperation indicates an expected call of LogOperation.
func (mr *MockEmitterMockRecorder) LogOperation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogOperation", reflect.TypeOf((*MockEmitter)(nil).LogOperation), arg0)
}
