apiVersion: v1
data:
  source: alpha
kind: ConfigMap
metadata:
  annotations:
    crossplane.io/composition-resource-name: cm
  creationTimestamp: "2026-04-29T17:56:03Z"
  labels:
    crossplane.io/composite: example
  name: alpha-output
  namespace: default
  ownerReferences:
  - apiVersion: example.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: XWidget
    name: example
    uid: 6fb3be6f-c579-42d1-8f8a-313832286405
  resourceVersion: "8803"
  uid: 9cc3ddde-2e0f-4ea1-8947-40dc50e44293
