// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tgoodwin/sleeve/pkg/tracecheck (interfaces: TriggerHandler)

// Package tracecheck is a generated GoMock package.
package tracecheck

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTriggerHandler is a mock of TriggerHandler interface.
type MockTriggerHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerHandlerMockRecorder
}

// MockTriggerHandlerMockRecorder is the mock recorder for MockTriggerHandler.
type MockTriggerHandlerMockRecorder struct {
	mock *MockTriggerHandler
}

// NewMockTriggerHandler creates a new mock instance.
func NewMockTriggerHandler(ctrl *gomock.Controller) *MockTriggerHandler {
	mock := &MockTriggerHandler{ctrl: ctrl}
	mock.recorder = &MockTriggerHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerHandler) EXPECT() *MockTriggerHandlerMockRecorder {
	return m.recorder
}

// GetTriggered mocks base method.
func (m *MockTriggerHandler) GetTriggered(arg0 Changes) ([]PendingReconcile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTriggered", arg0)
	ret0, _ := ret[0].([]PendingReconcile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTriggered indicates an expected call of GetTriggered.
func (mr *MockTriggerHandlerMockRecorder) GetTriggered(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTriggered", reflect.TypeOf((*MockTriggerHandler)(nil).GetTriggered), arg0)
}

// KindDepsForReconciler mocks base method.
func (m *MockTriggerHandler) KindDepsForReconciler(arg0 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KindDepsForReconciler", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KindDepsForReconciler indicates an expected call of KindDepsForReconciler.
func (mr *MockTriggerHandlerMockRecorder) KindDepsForReconciler(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KindDepsForReconciler", reflect.TypeOf((*MockTriggerHandler)(nil).KindDepsForReconciler), arg0)
}
