apiVersion: v1
data:
  source: alpha
kind: ConfigMap
metadata:
  annotations:
    crossplane.io/composition-resource-name: cm
  creationTimestamp: "2026-04-29T17:54:21Z"
  labels:
    crossplane.io/composite: example
  name: alpha-output
  namespace: default
  ownerReferences:
  - apiVersion: example.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: XWidget
    name: example
    uid: 103a1627-c39e-42eb-8f2b-25f11608f919
  resourceVersion: "8459"
  uid: 96a533ff-ad0b-4f8d-8fa9-dfc3ca218723
