apiVersion: example.org/v1
kind: XWidget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"example.org/v1","kind":"XWidget","metadata":{"annotations":{},"name":"example"},"spec":{"compositionRef":{"name":"widget-composition-alpha"},"compositionRevisionRef":{"name":"widget-composition-alpha-a39f01a"},"compositionUpdatePolicy":"Manual","message":"F1 audit"}}
  creationTimestamp: "2026-04-29T17:54:21Z"
  finalizers:
  - composite.apiextensions.crossplane.io
  generation: 2
  labels:
    crossplane.io/composite: example
  name: example
  resourceVersion: "8463"
  uid: 103a1627-c39e-42eb-8f2b-25f11608f919
spec:
  compositionRef:
    name: widget-composition-alpha
  compositionRevisionRef:
    name: widget-composition-alpha-a39f01a
  compositionUpdatePolicy: Manual
  message: F1 audit
  resourceRefs:
  - apiVersion: v1
    kind: ConfigMap
    name: alpha-output
    namespace: default
status:
  conditions:
  - lastTransitionTime: "2026-04-29T17:54:21Z"
    observedGeneration: 2
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2026-04-29T17:54:21Z"
    message: 'Unready resources: cm'
    observedGeneration: 2
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2026-04-29T17:54:21Z"
    observedGeneration: 2
    reason: WatchCircuitClosed
    status: "True"
    type: Responsive
